name: Continuous Deployment

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-nightly:
    name: Build branch {{}} on ${{ matrix.os }}, for ${{ matrix.rust }} rust
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [nightly, stable]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Install toolchain
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@v2
        with:
          name: stickerquest-${{matrix.os}}-${{matrix.rust}}-${{github.sha}}
          path: target/release
